CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_phone_key" ON "users"("phone");
CREATE INDEX "users_role_status_idx" ON "users"("role", "status");
CREATE UNIQUE INDEX "companies_ownerId_key" ON "companies"("ownerId");
CREATE INDEX "user_documents_userId_status_idx" ON "user_documents"("userId", "status");
CREATE UNIQUE INDEX "vehicles_plateNumber_key" ON "vehicles"("plateNumber");
CREATE INDEX "vehicles_companyId_status_idx" ON "vehicles"("companyId", "status");
CREATE INDEX "vehicles_type_status_isAvailable_idx" ON "vehicles"("type", "status", "isAvailable");
CREATE INDEX "vehicle_docs_vehicleId_expiresAt_idx" ON "vehicle_docs"("vehicleId", "expiresAt");
CREATE INDEX "vehicle_docs_vehicleId_status_idx" ON "vehicle_docs"("vehicleId", "status");
CREATE INDEX "transport_requests_senderId_status_idx" ON "transport_requests"("senderId", "status");
CREATE INDEX "transport_requests_originCountry_destCountry_status_idx" ON "transport_requests"("originCountry", "destCountry", "status");
CREATE INDEX "transport_requests_pickupDate_status_idx" ON "transport_requests"("pickupDate", "status");
CREATE INDEX "missions_carrierId_status_idx" ON "missions"("carrierId", "status");
CREATE INDEX "missions_requestId_idx" ON "missions"("requestId");
CREATE INDEX "commercial_deals_buyerId_status_idx" ON "commercial_deals"("buyerId", "status");
CREATE INDEX "commercial_deals_sellerId_status_idx" ON "commercial_deals"("sellerId", "status");
CREATE INDEX "commercial_deals_linkedMissionId_idx" ON "commercial_deals"("linkedMissionId");
CREATE UNIQUE INDEX "payments_gatewayTxId_key" ON "payments"("gatewayTxId");
CREATE INDEX "payments_payerId_status_idx" ON "payments"("payerId", "status");
CREATE INDEX "payments_missionId_idx" ON "payments"("missionId");
CREATE INDEX "payments_dealId_idx" ON "payments"("dealId");
CREATE UNIQUE INDEX "customs_requirements_originCountry_destCountry_goodsCategor_key" ON "customs_requirements"("originCountry", "destCountry", "goodsCategory");
CREATE INDEX "customs_dossiers_missionId_status_idx" ON "customs_dossiers"("missionId", "status");
CREATE INDEX "customs_documents_dossierId_status_idx" ON "customs_documents"("dossierId", "status");
CREATE INDEX "customs_documents_uploadedBy_idx" ON "customs_documents"("uploadedBy");
CREATE INDEX "messages_missionId_sentAt_idx" ON "messages"("missionId", "sentAt");
CREATE INDEX "messages_dealId_sentAt_idx" ON "messages"("dealId", "sentAt");
CREATE INDEX "messages_senderId_idx" ON "messages"("senderId");
CREATE INDEX "notifications_userId_readAt_idx" ON "notifications"("userId", "readAt");
CREATE INDEX "reviews_revieweeId_idx" ON "reviews"("revieweeId");
CREATE UNIQUE INDEX "reviews_missionId_reviewerId_key" ON "reviews"("missionId", "reviewerId");
CREATE INDEX "leads_type_createdAt_idx" ON "leads"("type", "createdAt");
